---
deployment:
  tasks:
    # Set deployment path
    - export DEPLOYPATH=/home1/xzqjfkmy/public_html/

    # Install dependencies and build the site before deployment
    - npm ci
    - npm run build

    # Deploy the freshly built assets
    - ./scripts/cpanel-deploy.sh "$DEPLOYPATH"
