---
deployment:
  tasks:
    # Set deployment path
    - export DEPLOYPATH=/home1/xzqjfkmy/public_html/

    # Deploy the site via a helper script that skips anything that is missing
    - ./scripts/cpanel-deploy.sh "$DEPLOYPATH"
